---
title: "p8105_hw3_xz3298"
author: "xinyi zheng"
date: "2023-10-08"
output: github_document
---
##Problem1
```{r}
library(p8105.datasets)
data("instacart")
<<<<<<< HEAD
head(instacart)
=======
data("instacart")
instacart = 
  instacart |> 
  as_tibble()

head(instacart)

>>>>>>> 02a0e78 (update new files)
library(dplyr)
library(ggplot2)
library(tidyverse)
```
##1)
```{r}
<<<<<<< HEAD
aisle_counts = instacart |>
  count(aisle, sort = TRUE)

num_aisles = nrow(aisle_counts)
top_aisles = head(aisle_counts, 5)

list(Number_of_Aisles = num_aisles, Top_Aisles = top_aisles)
=======
instacart |> 
  count(aisle) |> 
  arrange(desc(n))
>>>>>>> 02a0e78 (update new files)
```
##2)
```{r}
filtered_aisles = aisle_counts |>
  filter(n > 10000) |>
  arrange(-n)

ggplot(data=filtered_aisles, aes(x=reorder(aisle, n), y=n)) +
  geom_bar(stat="identity") +
  coord_flip() +
  labs(title="Number of items ordered in each aisle", x="Aisle", y="Number of Orders")
```
##3)
```{r}
selected_aisles = c("baking ingredients", "dog food care", "packaged vegetables fruits")

popular_items = instacart |>
  filter(aisle %in% selected_aisles) |>
  count(aisle, product_id, sort = TRUE) |>
  group_by(aisle) |>
  slice_head(n = 3) |>
  ungroup()

popular_items
```
##4)
```{r}
selected_products = c("Pink Lady Apples", "Coffee Ice Cream")

mean_order_time = instacart |>
  filter(product_id %in% selected_products) |>
  group_by(product_id, order_dow) |>
  summarize(mean_hour = mean(order_hour_of_day, na.rm = TRUE), .groups = 'drop') |>
  pivot_wider(names_from = order_dow, values_from = mean_hour)

print(colnames(mean_order_time))

```

##Problem2
```{r}
library(p8105.datasets)
data("brfss_smart2010")
head(brfss_smart2010)
library(dplyr)
```
#Data cleaning
```{r}
names(brfss_smart2010)

brfss_smart2010 = janitor::clean_names(brfss_smart2010)
names(brfss_smart2010)

library(p8105.datasets)
library(dplyr)

brfss_cleaned = brfss_smart2010 |>
  filter(topic == "Overall Health") |>
  filter(response %in% c("Poor", "Fair", "Good", "Very Good", "Excellent")) |>
  mutate(response = factor(response, 
                           levels = c("Poor", "Fair", "Good", "Very Good", "Excellent"), 
                           ordered = TRUE))

brfss_cleaned

```
##Answering questions
##1)
```{r}
library(dplyr)

# 2002
states_2002 <- brfss_smart2010 |>
  filter(year == 2002) |>
  group_by(locationabbr) |>
  summarize(locations = n()) |>
  filter(locations >= 7)

# 2010
states_2010 <- brfss_smart2010 |>
  filter(year == 2010) |>
  group_by(locationabbr) |>
  summarize(locations = n()) |>
  filter(locations >= 7)

states_2002
states_2010

```
##2)
```{r}
excellent_data <- brfss_smart2010 |>
  filter(response == "Excellent") |>
  group_by(year, locationabbr) |>
  summarize(avg_data_value = mean(data_value, na.rm = TRUE))

# Spaghetti Plot
library(ggplot2)

ggplot(excellent_data, aes(x = year, y = avg_data_value, group = locationabbr, color = locationabbr)) +
  geom_line() +
  labs(title = "Average Value of 'Excellent' Responses Over Time by State", 
       y = "Average Data Value") +
  theme(legend.position = "none")
```
##3)
```{r}
ny_data <- brfss_smart2010 |>
  filter(year %in% c(2006, 2010), locationabbr == "NY", response %in% c("Poor", "Fair", "Good", "Very Good", "Excellent"))

ggplot(ny_data, aes(x = response, y = data_value)) +
  geom_boxplot() +
  facet_wrap(~ year) +
  labs(title = "Distribution of Data Value for Responses in NY (2006 & 2010)", 
       y = "Data Value",
       x = "Response")
```

##Problem3
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```
##tidy data
```{r}
accel_data <- read.csv("data/nhanes_accel.csv")
demo_data <- read.csv("data/nhanes_covar.csv", skip = 4)

merged_data <- inner_join(accel_data, demo_data, by = "SEQN")

tidied_data <- merged_data |>
  filter(age >= 21) |>
  drop_na(sex, education)

head(tidied_data)
```
##give a read friendly table
```{r}
education_sex_table <- knitr::kable(tidied_data, caption = "The number of men and women in each education category")

<<<<<<< HEAD
=======
datatable

>>>>>>> 02a0e78 (update new files)
print(education_sex_table)
```
##visualization of the age distributions for men and women in each education category
```{r}
education_data <- tidied_data |>
  group_by(education)
##plot
education_data |>
  ggplot(aes(x = age, y = education, color = sex)) +
  geom_smooth()
```
##Total activity Visualization
```{r}
total_activity_data <- tidied_data |>
  group_by(SEQN)
##plot
total_activity_data |>
  ggplot(aes(x = age, y = , color = sex)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ education) +
  labs(title = "Total Activity vs. Age by Education and Gender",
       x = "Age", y = "Total Activity") +
  theme_minimal()

```
##24 hour visualization
```{r}
time_course_data <- tidied_data |>
  group_by(SEQN, education, sex)
##plot
time_course_data |>
  ggplot(aes(x = SEQN, y = avg_activity, color = sex)) +
  geom_line() +
  geom_smooth(se = FALSE) +
  facet_wrap(~ education) +
  labs(title = "24-Hour Activity by Education and Sex",
       x = "Time", y = "Average Activity") +
  theme_minimal()

```

